### ISSUE TITLE
hellp

### ISSUE THREAD

**Issue by yurayu1985** [Mffff4/qlyukerbot#2]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic_settings\sources.py", line 323, in __call__
    field_value = self.prepare_field_value(field_name, field, field_value, value_is_complex)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic_settings\sources.py", line 513, in prepare_field_value
    raise e
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic_settings\sources.py", line 510, in prepare_field_value
    value = self.decode_complex_value(field_name, field, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic_settings\sources.py", line 147, in decode_complex_value
    return json.loads(value)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ShitCoinTapBot\qlyukerbot\qlyukerbot\main.py", line 5, in <module>
    from bot.utils.launcher import process
  File "C:\ShitCoinTapBot\qlyukerbot\qlyukerbot\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\ShitCoinTapBot\qlyukerbot\qlyukerbot\bot\utils\launcher.py", line 12, in <module>
    from bot.config import settings
  File "C:\ShitCoinTapBot\qlyukerbot\qlyukerbot\bot\config\__init__.py", line 1, in <module>
    from .config import settings
  File "C:\ShitCoinTapBot\qlyukerbot\qlyukerbot\bot\config\config.py", line 80, in <module>
    settings = Settings()
               ^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic_settings\main.py", line 85, in __init__
    **__pydantic_self__._settings_build_values(
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic_settings\main.py", line 187, in _settings_build_values
    return deep_update(*reversed([source() for source in sources]))
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic_settings\main.py", line 187, in <listcomp>
    return deep_update(*reversed([source() for source in sources]))
                                  ^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic_settings\sources.py", line 685, in __call__
    data: dict[str, Any] = super().__call__()
                           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic_settings\sources.py", line 325, in __call__
    raise SettingsError(
pydantic_settings.sources.SettingsError: error parsing value for field "TAPS" from source "DotEnvSettingsSource"

**Comment by 01M** [comment]
+

**Comment by Mffff4** [comment]
Напиши, например, TAPS=[15,50]

**Comment by Mffff4** [comment]
21
